version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "make start"
    ports:
      - '4040:3000'
    volumes:
      - '~/.bash_history:/.bash_history'
      - './services/app:/usr/src/app:cached'
      - '/tmp:/tmp:delegated'
