version: '3.3'

services:
  app:
    build:
      context: services/app
      dockerfile: Dockerfile.development
    command: sh -c "rm -f /usr/src/app/tmp/pids/server.pid && make start"
    expose:
      - "3000"
    volumes:
      - '~/.bash_history:/.bash_history'
      - './services/app:/usr/src/app:cached'
      - '/tmp:/tmp:delegated'
  nginx:
    build:
      context: services/nginx
    ports:
      - "80:80"
    depends_on:
      - app
