FROM starefossen/ruby-node

ENV PROJECT_ROOT /usr/src/app

WORKDIR $PROJECT_ROOT

COPY Gemfile Gemfile
COPY Gemfile.lock Gemfile.lock

RUN bundle install --path vendor/bundle

COPY . .

RUN bundle exec rake assets:precompile